version: "3"

services:
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=provi
      - POSTGRES_PASSWORD=provi

volumes:
  postgres:
